#!/bin/bash

echo "===== Homebrew Installation Guide ====="
echo ""
echo "Homebrew requires administrator privileges to install."
echo "Please follow these steps:"
echo ""
echo "1. Open Terminal (if you're not already in it)"
echo ""
echo "2. Run the following command to install Homebrew:"
echo "   /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo ""
echo "3. When prompted, enter your administrator password"
echo ""
echo "4. After installation, Homebrew might ask you to run additional commands to add it to your PATH."
echo "   Make sure to run those commands."
echo ""
echo "5. Verify the installation by running:"
echo "   brew --version"
echo ""
echo "6. Once Homebrew is installed, run the following commands to install Node.js and other dependencies:"
echo "   brew install node"
echo "   brew install mosquitto  # MQTT broker for Shelly devices"
echo ""
echo "7. After installing Node.js, run the setup script to configure the Shelly Smart Home application:"
echo "   ./setup-node.sh"
echo ""
echo "===== End of Guide ====="
